language: c++

before_script:
  - wget -q https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.1/wxWidgets-3.1.1.tar.bz2
  - tar jxf wxWidgets-3.1.1.tar.bz2
  - cd wxWidgets-3.1.1
  - ./configure --prefix=$HOME/wx-3.1.1 --enable-shared=no --enable-stl=yes --enable-debug=no --with-gtk=2 --with-libjpeg=builtin --with-libpng=builtin --with-regex=builtin --with-libtiff=builtin --with-zlib=builtin --with-expat=builtin --without-libjbig --without-liblzma --without-gtkprint --with-libnotify=no --with-libmspack=no --with-gnomevfs=no --with-opengl=yes --with-sdl=no --with-cxx=11
  - make -j2 all install
  - ln -s $HOME/wx-3.1.1/bin/wx-config $HOME/wx-3.1.1/bin/wx-config-3
  - user=$(echo $TRAVIS_REPO_SLUG | sed 's,/.*$,,')
  - (cd ../ && pwd)
 # - export GTEST=/home/travis/build/$user/googletest/googletest
  - export LKDIR=/home/travis/build/$user/lk
  - export WEXDIR=/home/travis/build/$user/wex
  - export SSCDIR=/home/travis/build/$user/ssc
  - export SAMNTDIR=/home/travis/build/$user/SAM
 # - git clone https://github.com/google/googletest /home/travis/build/$user/googletest
  - git clone https://github.com/$user/lk $LKDIR
  - git clone https://github.com/$user/wex $WEXDIR
  - git clone https://github.com/$user/ssc $SSCDIR
  
script:
  - export PATH=$PATH:$HOME/wx-3.1.1/bin
 # - make -C $GTEST/make
  - make -C $LKDIR/build_linux
  - make -C $WEXDIR/build_linux
  - make -C $SSCDIR/build_linux
  - make -C $SAMNTDIR/build_linux

install:
  - sudo apt-get install -y libgtk2.0-dev libgl1-mesa-dev mesa-common-dev freeglut3-dev libcurl4-openssl-dev libc6

branches:
  only:
  - master
  - develop
  - Host_Developer
  - weather_forecast
  - bifacial
